### ISSUE TITLE
ResourceNotFoundException 

### ISSUE THREAD

**Issue by twigs67** [hardyscc/nestjs-dynamoose#108]
Hello,

I'm new to DybamoDB, so I imagine this is working as expected, but I'm getting a ResourceNotFoundException. 

The table DOES NOT exist in DynamoDB, so this error is technically accurate, but I didn't think it would throw this error. Do tables have to exist in DynamoDB for this to work?

Thanks

**Comment by hardyscc** [comment]
The table will create automatically, however you disable it by setting the forRoot options  
`{ model: { create: false } }`
