### ISSUE TITLE
Example of searching with range/sort key?

### ISSUE THREAD

**Issue by twigs67** [hardyscc/nestjs-dynamoose#109]
Hello,

I'm trying to search with a range/sort key using the example boilerplate, but I keep getting "The provided key element does not match the schema". 

Could you provide an example of how you would query with the following schema:

```
import { Schema } from 'dynamoose';

export const NotificationSchema = new Schema({
  id: {
    type: String,
    hashKey: true,
  },
  targetId: {
    type: String,
    index: {
      global: true,
      rangeKey: 'status',
    },
  },
  userId: {
    type: String,
    index: {
      global: true,
      rangeKey: 'status',
    },
  },
  content: {
    type: String,
  },
  status: {
    type: String,
  },
  createAt: {
    type: String,
    rangeKey: true,
  },
});
```

* createAt is the rangeKey.

**Comment by hardyscc** [comment]
You cannot query the rangKey without the hashKey, from your schema design you can only use scan.

**Comment by twigs67** [comment]
Thanks for the quick response and putting up with my questions.
