### ISSUE TITLE
Invalid order in ts type

### ISSUE THREAD

**Issue by Nesty92** [hardyscc/nestjs-dynamoose#184]
The UpdateTransaction interface is type `<Key, Data>` 
https://github.com/hardyscc/nestjs-dynamoose/blob/2cbba4774f1f43a858a748a4a4c12b835878c642/lib/interfaces/model.interface.ts#L409
then in the TrasactionType you use `<Data, Key>` 
https://github.com/hardyscc/nestjs-dynamoose/blob/2cbba4774f1f43a858a748a4a4c12b835878c642/lib/interfaces/model.interface.ts#L436
This line should be:
```typescrypt
update: UpdateTransaction<Key, Data>;
```
this produce a error when typescript try to match the updateObj object as the keyObj 
`
 Overload 1 of 5, '(keyObj: DBProfileItem, updateObj: Partial<DBProfileKey>): UpdateTransactionResult', gave the following error.
    Argument of type 'DBProfileKey' is not assignable to parameter of type 'DBProfileItem'.
      Type 'DBProfileKey' is missing the following properties from type 'DBProfileItem': photo, email, firstName, lastName
  Overload 2 of 5, '(keyObj: DBProfileItem, updateObj?: Partial<DBProfileKey>, settings?: ModelUpdateSettings): UpdateTransactionResult', gave the following error.
    Argument of type 'DBProfileKey' is not assignable to parameter of type 'DBProfileItem'.
`

**Comment by hardyscc** [comment]
@Nesty92 Thanks for your report, fix and released as v0.2.9
