### ISSUE TITLE
Add support for serializers 

### ISSUE THREAD

**Issue by andrewda** [hardyscc/nestjs-dynamoose#236]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Dynamoose supports adding custom serializers, like so:

```ts
User.serializer.add("myCustomSerializer", {
	include: ["email"]
});

...

myUser.serialize("myCustomSerializer");
```

However, there are no type definitions for serializers in `nestjs-dynamoose`

## Expected behavior

I think something like this might be a good way to define serializers in NestJS:

```ts
DynamooseModule.forFeature([{
	name: 'User',
	schema: UserSchema,
	serializers: {
		"myCustomSerializer": { include: ["email"] },
	},
}])

...

myUser.serialize("myCustomSerializer");
```

Alternatively, `forFeature` might accept an already-defined `Model`, which could have serializers defined before being passed in the import.

**Comment by hardyscc** [comment]
@andrewda do u mind to take a look of this PR?
