### ISSUE TITLE
[Q] best practices "nestjs-dynamoose" <> "single table"

### ISSUE THREAD

**Issue by CrystalMethod** [hardyscc/nestjs-dynamoose#291]
I am very interested in your best practices in the use of `nestjs-dynamoose`. Especially in the context of the "single table" pattern. NestJs basically offers the concepts: Module, Controller, Service. If, for example, `n` different types of entities are stored in the "single table", I can split the NestJS modules as follows:

```
1-x Module -> n-x Controller -> n-x Service (per Model)

n-x Module -> 1-x Controller -> 1-x Service (per Model)
```

While the first approach seems very monolithic, the second is probably too fine-granular. But let's start with the "n-x Module" approach, i.e. one Module == one Document (aka Entity) Type:

`FooModule.ts`:
```js
@Module({
  imports: [
    DynamooseModule.forFeature([{ name: 'single-table', schema: [ FooSchema ]}]),
  ]
  ...
```
`BarModule.ts`:
```js
@Module({
  imports: [
    DynamooseModule.forFeature([{ name: 'single-table', schema: [ BarSchema ]}]),
  ]
  ...
```
This looks reasonable, at least as long the types of entities dont overlap functionality. If I really need functionality from another module, I simply import the related services as follows:

`BazModule.ts`:
```js
@Module({
  imports: [
    DynamooseModule.forFeature([{ name: 'single-table', schema: [ BazSchema ]}]),
    FooService,
    BarService
  ]
  ...
```
But what if I need to utilize transactions? The exported services from other modules don't help here, because transactions are implemented on Model level not on Service level.

`TransactionalBazModule.ts`:
```js
@Module({
  imports: [
    DynamooseModule.forFeature([{ name: 'single-table', schema: [ FooSchema, BarSchema, BazSchema ]}])
  ]
  ...
```
`BazService.ts`:
```js
@Injectable()
export class BazService extends TransactionSupport {
  constructor(
    @InjectModel('single-table')
    private fooModel: Model<Foo, FooKey>,
    @InjectModel('single-table')
    private barModel: Model<Bar, BarKey>,
    @InjectModel('single-table')
    private bazModel: Model<Baz, BazKey>,
  ) {
    super();
  }

  async create(foo: Foo, bar: Bar, baz: Baz) {
    await this.transaction([
      this.fooModel.transaction.create(foo),
      this.barModel.transaction.create(bar),
      this.bazModel.transaction.create(baz),
    ]);
  }
}
...
```

**Comment by hardyscc** [comment]
@CrystalMethod you can create a SharedModule like that

```ts
import { Global, Module } from '@nestjs/common';
import { DynamooseModule } from 'nestjs-dynamoose';

@Global()
@Module({
  imports: [
    DynamooseModule.forFeature([
      { name: 'single-table', schema: [FooSchema, BarSchema, BazSchema] },
    ]),
  ],
  exports: [DynamooseModule],
})
export class SharedModule {}
```

import it under your app.module.ts, then the Models can be shared for all other modules.

```ts
import { DynamooseModule } from 'nestjs-dynamoose';
import { SharedModule } from './shared.module';

@Module({
 imports: [
   DynamooseModule.forRoot(),
   SharedModule,
   FooModule,
   BarModule,
   BazModule,
 ],
})
export class AppModule {}
```

For more details about shared module please see https://docs.nestjs.com/modules#shared-modules

**Comment by CrystalMethod** [comment]
Hi @hardyscc. Thank you for your answer and the explanation about the integration in NestJS. I was able to try this out in the meantime and can confirm that it works as described. I am still relatively new in the use of NestJS and I was not so familiar with the use of global modules and re-exports. Regards.

**Comment by kisanme** [comment]
@hardyscc How would I go about having multiple models in a single database? I can define them but they are referenced by the table name. Isn't there a way to define a different model name and a different table name?

Basically, I need to have different entities in the database represented as different modules in NestJS.

**Comment by hardyscc** [comment]
@kisanme  I am not quite understand what u means, but do u want like that? 

```ts
import { Global, Module } from '@nestjs/common';
import { DynamooseModule } from 'nestjs-dynamoose';

@Module({
  imports: [
    DynamooseModule.forFeature([
      { name: 'foo-table', schema: FooSchema },
      { name: 'bar-table', schema: BarSchema },
      { name: 'baz-table', schema: BazSchema },
    ]),
  ],
})
export class YourModule {}
```

**Comment by kisanme** [comment]
@hardyscc I mean I'd like to have a single table containing multiple schemas. When using this name attribute it tries to find out a table with that name. But I need a single table containing different schemas.

**Comment by hardyscc** [comment]
@kisanme yes dynamoose support multiple schemas in single table, please see https://dynamoosejs.com/guide/Model/#dynamoosemodeldocumentname-schema

so u can do the same here
```ts
import { Global, Module } from '@nestjs/common';
import { DynamooseModule } from 'nestjs-dynamoose';

@Module({
  imports: [
    DynamooseModule.forFeature([
      { name: 'single-table', schema: [FooSchema, BarSchema, BazSchema] },
    ]),
  ],
})
export class YourModule {}
```
later u can inject each of the Model

```ts
@Injectable()
export class BazService extends TransactionSupport {
  constructor(
    @InjectModel('single-table')
    private fooModel: Model<Foo, FooKey>,
    @InjectModel('single-table')
    private barModel: Model<Bar, BarKey>,
    @InjectModel('single-table')
    private bazModel: Model<Baz, BazKey>,
  ) {
    super();
  }
}
```

**Comment by kisanme** [comment]
Thanks, it works. 

One caveat is the Type definition of the Model doesn't really match their corresponding document from the DynamoDB database. If there exists an attribute shared in between two schemas; it always chooses the first schema in the definition; not the typed model injected.

**Comment by hardyscc** [comment]
@kisanme yes the model type is just the compile time hints, it doesn't effect the runtime behaviour.

**Comment by youngkiu** [comment]
Among `FooSchema, BarSchema, and BazSchema`
If only one schema has the required attribute, the following error occurs:

```
ValidationError: <Attribute> is a required property but has no value when trying to save item
    at Schema.requiredCheck (<PATH>/node_modules/dynamoose/dist/Schema.js:866:15)
    at check (<PATH>/node_modules/dynamoose/dist/Item.js:523:30)
    at <PATH>/node_modules/dynamoose/dist/Item.js:535:23
    at Array.map (<anonymous>)
    at Function.Item.objectFromSchema (<PATH>/node_modules/dynamoose/dist/Item.js:520:45)
    at Item.toDynamo (<PATH>/node_modules/dynamoose/dist/Item.js:558:20)
    at Object.accumulator.<computed> [as create] (<PATH>/node_modules/dynamoose/dist/Model/index.js:242:30)
    at async Promise.all (index 0)
    at <PATH>/node_modules/dynamoose/dist/Transaction.js:35:36
    at UserRepository.create
```

**Comment by hardyscc** [comment]
@youngkiu
I believe this is the correct behavior: the required property needs to be satisfied in all the schemas for the single-table approach.

**Comment by JhonatanZ-Gueno** [comment]
Just FYI I had the same problema and I had to define the module on this way:

```typescript
import { Module } from '@nestjs/common';
import { DynamooseModule } from 'nestjs-dynamoose';

@Module({
  imports: [
    DynamooseModule.forFeature([{
      name: 'Foo',
      schema: [FooSchema],
      options: {
        tableName: 'table-name'
      }
    }]),
    DynamooseModule.forFeature([{
      name: 'Bar',
      schema: [BarSchema],
      options: {
        tableName: 'table-name'
      }
    }]),
    DynamooseModule.forFeature([{
      name: 'Baz',
      schema: [BazSchema],
      options: {
        tableName: 'table-name'
      }
    }]),
  ],
})
export class YourModule {}
``` 

```typescript
@Injectable()
export class BazService extends TransactionSupport {
  constructor(
    @InjectModel('Foo')
    private fooModel: Model<Foo, FooKey>,
    @InjectModel('Bar')
    private barModel: Model<Bar, BarKey>,
    @InjectModel('Baz')
    private bazModel: Model<Baz, BazKey>,
  ) {
    super();
  }
}
```
