### ISSUE TITLE
Create schema with a model type

### ISSUE THREAD

**Issue by MRdgz** [hardyscc/nestjs-dynamoose#363]
Hello, I"m having trouble creating a schema that has a different model as a type for one of its properties. Similar to how it is documented here https://dynamoosejs.com/guide/Schema#model-types for the gameSchema 

As far as I understand, I don't have access to the user model object that is being created when I pass the schema to DynamooseModule.forFeature()

Is there a way to do this currently? Thank you!

**Comment by hardyscc** [comment]
@MRdgz  i don't know this will work or not, but u could have a try.


```js
import { model, Schema, THIS } from 'dynamoose';

export const UserSchema = new Schema({
  id: String,
  name: String,
  parent: THIS,
});

export const GameSchema = new Schema({
  id: String,
  state: String,
  user: model('User', UserSchema),
});
```

```js
import { UserSchema, GameSchema } from './schema'

@Module({
  imports: [
    DynamooseModule.forFeature([
      {
        name: 'user',
        schema: UserSchema,
      },
      {
        name: 'game',
        schema: GameSchema,
      },
    ]),
  ],
  ...
})



```

**Comment by MRdgz** [comment]
Thanks,  I'll let you know if this works!

**Comment by MRdgz** [comment]
It didn't work. At compile time, an ` UnhandledPromiseRejectionWarning: ConfigError: Missing region in config`  warning is shown.

**Comment by MRdgz** [comment]
I've also tried the following with `GameSchema(model).getSchema()` returning a schema instance.  Using this method. It no longer generates the warning from above but says that `user` is an unknown property when trying to store new information. I did notice that during compile, the factory is running twice. The first has `model` as undefined, and the second time `model` is actually defined. 
```TSX
@Module({
  imports: [
    DynamooseModule.forFeatureAsync([
      {
        name: 'User',
        useFactory: () => UserSchema,
      },
      {
        name: 'Game',
        useFactory: (model) => new GameSchema(model).getSchema(),
        inject: ['UserModel'],
      },
    ]),
]})
```

**Comment by hardyscc** [comment]
@MRdgz I just tested the factory should only called once, 
also the model should be passed as the second arg, so please try this example if this works for u

```js
export const GameSchemaDef = {
  id: String,
  state: String,
}
```

```js
@Module({
  imports: [
    DynamooseModule.forFeatureAsync([
      {
        name: 'User',
        useFactory: () => UserSchema,
      },
      {
        name: 'Game',
        useFactory: (_, model) => new Schema({ ...GameSchemaDef, user: model }),
        inject: ['UserModel'],
      },
    ]),
]})
```

**Comment by elijahmg** [comment]
@hardyscc @MRdgz will join here. Have same problem right now. I tried both solutions, and getting same error as above `ConfigError: Missing region in config`

**Comment by elijahmg** [comment]
Sorry for miss-leading message, but the last example is worked for me

**Comment by MRdgz** [comment]
Thank you, the solution above also worked for me! I will close the issue now! 😄

**Comment by nguyenjk** [comment]
> Thank you, the solution above also worked for me! I will close the issue now! 😄

@MRdgz do you have working sample? I tried the same but got error at compile time Type 'SchemaSettings' is missing the following properties from type 'AttributeDefinition[]
