### ISSUE TITLE
Improve documentation / readme

### ISSUE THREAD

**Issue by MickL** [hardyscc/nestjs-dynamoose#40]
- You import: `import { Schema } from 'dynamoose';` but this does not exist?
- In the 4th step you inject `constructor(@InjectModel('User') private userModel: Model<User>) {}` but where is `User` coming from?
- In the 4th step you inject `constructor(@InjectModel('User') private userModel: Model<User>) {}` but `Model<DataSchema, KeySchema>` requires two type arguments

Btw. could you add to the readme, just a sentence, what is the benefit of using this module over "plain" Dynamoose? E.g. `Dynamoose module for Nest. Use this to have dependency injection for your models.` or something like that.

**Comment by hardyscc** [comment]
Please check out https://github.com/hardyscc/aws-nestjs-starter first, it should solve all of your problems. Thank for point out should be Model<User, string> :)

**Comment by MickL** [comment]
May you update the readme, also for the first two things? User was not imported.

**Comment by hardyscc** [comment]
make sure you npm install `dynamoose@beta`  you should able to import it, also readme has been updated enjoy! 
please always refer to https://github.com/hardyscc/aws-nestjs-starter which is fully runnable project.

**Comment by MickL** [comment]
I am at beta.8 and i dont see any Schema to import. There is no ts declaration file at all that would export that. 

Could you add an import for the User in the readme, too? It is kind of using a class/interface without any import.

**Comment by hardyscc** [comment]
currently dynamoose v2 still not typed, so just add this line and ignore the type warning
```
import { Schema } from 'dynamoose'
```

the README.md has been updated, it included User class!

**Comment by MickL** [comment]
Thank you! 

The example looks a little bit overcomplicated now for me with GraphQL and the resolver. Personally I would remove the decorators from `user.model.ts`, remove `create-user.input.ts`, remove `user.resolver.ts` and then just showcase the basic usage with create and update in the `user.service.ts`. What do you think?

**Comment by hardyscc** [comment]
Yes I think so too, let's change it like that, can you test it for me?
```
import { Injectable } from '@nestjs/common';
import { InjectModel, Model } from 'nestjs-dynamoose';
import * as uuid from 'uuid';

interface User extends UserInput {
  id: string;
}

interface UserInput {
  name: string;
}

@Injectable()
export class UserService {
  constructor(
    @InjectModel('User')
    private userModel: Model<User, string>,
  ) {}

  create(input: UserInput) {
    return this.userModel.create({
      ...input,
      id: uuid.v4(),
    });
  }

  update(id: string, input: UserInput) {
    return this.userModel.update(id, input);
  }
}
```

**Comment by hardyscc** [comment]
some mistake, the KeySchema need to an object `Model<User, { id: string }>`
please refer to  https://github.com/hardyscc/aws-nestjs-starter for the model.update example.
I will also simplify the readme as well, thanks for your suggestion!

**Comment by MickL** [comment]
Looks good! I dont understand this tho:  `type User = UserKey & UserInput;`

**Comment by hardyscc** [comment]
This is typescript intersection types

**Comment by MickL** [comment]
Hey, looks good so far! Sorry if I am using this issue but I have some questions which are refering to the kind-of missing documentation:

Can you please explain these two generics: `interface Model<DataSchema, KeySchema>` ?

Is DataSchema my Schema as a TypeScript interface? If so, do I have full typing? That would be awesome! But what is KeySchema? Can I also define the hashKey (partition key) and rangeKey (sort key) in there? If yes how to seperate them?

One more thing that was missing in the documentation is that `DynamooseModule.forRoot` has options, and which (`DynamooseModuleOptions`) and `DynamooseModule.forFeature` models have options and which (`ModelOptions`). I just figured this out by clicking on the TypeScript interfaces in my IDE.

**Comment by MickL** [comment]
I tried around a little bit and I think I get `DataSchema` and `KeySchema` now and why you used `type User = UserKey & UserInput;`. This is kind of a genius to have this type checking! Anyway imo this might be explained in the readme.

**Comment by MickL** [comment]
Added a PR. Comments are welcome :)

**Comment by hardyscc** [comment]
Looks good for me, I will review the PR and merge it tomorrow... 
Thanks for your contribution!
