### ISSUE TITLE
Add typings to dynamoose project

### ISSUE THREAD

**Issue by MickL** [hardyscc/nestjs-dynamoose#41]
I saw you wrote typings for Model, Query, Scan, etc. thats awesome! Could you add the typings  to the Dynamoose root project instead?

So the root project has a index.d.ts and can be used within TypeScript projects with autocompletion, that would be awesome! :)

**Comment by hardyscc** [comment]
The original version of the type file is come from https://github.com/dynamoosejs/dynamoose, I am pretty sure @fishcharlie will include it once dynamoose v2 is completed.

**Comment by MickL** [comment]
Maybe I am stupid but I dont see this file anywhere. Can you link it?

**Comment by MickL** [comment]
Oh this is version 1. Interesting. But you adopted it for v2 right?

Could you add this file to v2 with your v2 typings maybe?

**Comment by fishcharlie** [comment]
Just commented on https://github.com/dynamoosejs/dynamoose/issues/785#issuecomment-610713543. Also checkout dynamoosejs/dynamoose#788.

**Comment by hardyscc** [comment]
@fishcharlie Thanks Charlie, looking forward for the 2.1 version :)
I found that most of the interfaces are the same as v1 for `Model` and `SchemaAttributes` type, I will temporary maintains those files here for convenience.

**Comment by fishcharlie** [comment]
@hardyscc Sounds good! If you have experience with TypeScript I'd love to maybe get your advice every once in a while if I run into problems. Still kinda new to TypeScript so for sure looking for people to be able to give advice from and to ask questions of every once in a while 😆. No pressure or anything tho.

**Comment by hardyscc** [comment]
@fishcharlie sure this is my pleasure!

**Comment by MickL** [comment]
Closing this in favor of dynamoosejs/dynamoose#785
