### ISSUE TITLE
Nestjs DynamooseModule.forFeatureAsync is throwing InvalidParameter exception - hashKey must be at root object and not nested in object or array

### ISSUE THREAD

**Issue by dhirajkumar94** [hardyscc/nestjs-dynamoose#449]
## I'm submitting a...
<pre><code>
[X] Bug report
</code></pre>

## Current behavior

Throwing the exception: hashKey must be at root object and not nested in object or array.

## Expected behavior

The code is working properly when I use the synchronous method to feature a schema as below:

<pre><code>
DynamooseModule.forFeature([
  { name: 'QA.B_BUREAU', schema: BureauSchema },
]),
</code></pre>

## Minimal reproduction of the problem with instructions

<pre><code>
import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { DynamooseModule } from 'nestjs-dynamoose';
import { BureauController } from './bureau.controller';
import { BureauSchema, dummySchema } from './bureau.schema';
import { BureauService } from './bureau.service';

@Module({
  imports: [
    DynamooseModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (configSvc: ConfigService) => ({
        aws: {
          accessKeyId: configSvc.get<string>('aws.dynamo.accessKeyId'),
          secretAccessKey: configSvc.get<string>('aws.dynamo.secretAccessKey'),
          region: configSvc.get<string>('aws.region')
        }
      }),
      inject: [ConfigService]
    }),
    DynamooseModule.forFeatureAsync([{
      imports: [ConfigModule],
      name: 'QA.B_BUREAU',
      useFactory: (configSvc: ConfigService) => ({
        name: 'QA.B_BUREAU',
        schema: BureauSchema,
      }),
      inject: [ConfigService],
    }])
  ],
  providers: [BureauService],
  controllers: [BureauController]
})
export class BureauModule {}
</code></pre>

## What is the motivation / use case for changing the behavior?

exception: hashKey must be at root object and not nested in object or array.

## Environment
<pre><code>
NestJS version: 8.1.1
NestJS Dynamoose version: 0.3.3
Dynamoose version: 2.8.2

 
For Tooling issues:
- Node version: 14.15.3
- Platform:  Mac, Linux
</code></pre>

**Comment by hardyscc** [comment]
@dhirajkumar94  FYI `tableName` will be added in v0.5.2
https://github.com/hardyscc/nestjs-dynamoose/issues/822#issuecomment-1499241711
