### ISSUE TITLE
Support for AWS Web identity token credentials ?

### ISSUE THREAD

**Issue by dejwsz** [hardyscc/nestjs-dynamoose#628]
Any option to support Web identity token credentials like it is mentioned here? https://npm.io/package/@aws-sdk/credential-provider-node. In such case such env variables are provided like AWS_WEB_IDENTITY_TOKEN_FILE, AWS_DEFAULT_REGION, AWS_REGION oraz AWS_ROLE_ARN and short lived tokens are used and automatically refreshed.
It is used often in EKS (AWS managed Kubernetes) and there is no need to exchange credentials like key id and secret key. So for container based apps it would be beneficial.

**Comment by hardyscc** [comment]
@dejwsz are you able to pass it through the `ddb` config 
https://dynamoosejs.com/getting_started/Configure#dynamoose-specific
if not please make feature request to [dynamoose](https://dynamoosejs.com/), since this project is just a wrapper of it.
