### ISSUE TITLE
Release dynamoose 2.1.x to npm

### ISSUE THREAD

**Issue by MickL** [hardyscc/nestjs-dynamoose#71]
Hey, could you release 0.2.0-beta to to latest in npm? So it is no more a beta?

Also feel free to join the Dynamoose Slack channel if you want :) https://join.slack.com/t/dynamoose/shared_invite/enQtODM4OTI0MTc1NDc3LWI3MmNhMThmNmJmZDk5MmUxOTZmMGEwNGQzNTRkMjhjZGJlNGM5M2JmZjMzMzlkODRhMGY3MTQ5YjQ2Nzg3YTY

**Comment by hardyscc** [comment]
I am waiting your PRs dynamoose/dynamoose#846, dynamoose/dynamoose#847 to merge before release it.

**Comment by MickL** [comment]
Good idea. But it should not effect nestjs-dynamoose since Dynamoose is a peer dependency anyway?

**Comment by hardyscc** [comment]
correct!

**Comment by MickL** [comment]
So we can just deploy this and dont care what Dynamoose does? I would remove the esModuleInterop here, too.

**Comment by hardyscc** [comment]
I don't want to add esModuleInterop in this project XD, that is why still in beta.
you can just use nestjs-dynamoose@0.1.6 with dynamoose@2.1.0 should works fine

**Comment by hardyscc** [comment]
nestjs-dynamoose@0.2.0 released
