### ISSUE TITLE
The DYNAMOOSE_MODULE_OPTIONS looks unnecessary in dynamoose-core.module.ts`

### ISSUE THREAD

**Issue by GeekEast** [hardyscc/nestjs-dynamoose#807]
In line 70 of `dynamoose-core.module.ts`
![CleanShot 2023-03-23 at 15 58 56@2x](https://user-images.githubusercontent.com/24806887/227111989-866c6d2d-f00f-4197-b581-f92aa03cf8c0.jpg)

it looks like the DYNAMOOSE_MODULE_OPTIONS has never been used as a provide token to inject anything.

Is it necessary here?

**Comment by hardyscc** [comment]
@GeekEast it is needed.
Since createAsyncOptionsProvider() function will provide the DYNAMOOSE_MODULE_OPTIONS for injection
