### ISSUE TITLE
Update interfaces to 2.2.0

### ISSUE THREAD

**Issue by MickL** [hardyscc/nestjs-dynamoose#81]
`Model.get(key, settings?, cb?)` now accepts an array of `attributes` in the settings:
https://dynamoosejs.com/guide/Model#modelgetkey-settings

And maybe other changes, see: https://github.com/dynamoose/dynamoose/releases

This brings me back to https://github.com/hardyscc/nestjs-dynamoose/issues/76 :)

**Comment by hardyscc** [comment]
@MickL It is done, check out version 0.2.2
