### ISSUE TITLE
ForFeatureAsync has weird interface

### ISSUE THREAD

**Issue by geekmini** [hardyscc/nestjs-dynamoose#822]
```typescript
export interface AsyncModelFactory extends Pick<ModuleMetadata, 'imports'>, Pick<ModelDefinition, 'name' | 'options' | 'serializers'> {
    useFactory: (...args: any[]) => ModelDefinition['schema'] | Promise<ModelDefinition['schema']>;
    inject?: any[];
}
```

the AsyncModelFactory should not have the `name` property, the `name`, `options`, `serializers` should be return from useFactory rather than define in AsyncModelFactory.

For example, if I am going to inject some values from `config`, there is no way to access to it outside `useFactory` function.

**Comment by hardyscc** [comment]
@geekmini the original design of the forFeatureAsync only support Schema, however it is ok to move options and serializers  inside the factory. however for the name property it is better remain the same as it is quite difficult to change without breaking the backward compatibility. what do you think?

`async-model-factory.interface.ts`

```diff
export interface AsyncModelFactory
  extends Pick<ModuleMetadata, 'imports'>,
    Pick<ModelDefinition, 'name' | 'options' | 'serializers'> {
  useFactory: (
    ...args: any[]
  ) =>
    | ModelDefinition['schema']
    | Promise<ModelDefinition['schema']>
+   | Omit<ModelDefinition, 'name'>
+   | Promise<Omit<ModelDefinition, 'name'>>;
  inject?: any[];
}
```

`dynamoose.providers.ts`

```ts
export function createDynamooseAsyncProviders(
  modelFactories: AsyncModelFactory[] = [],
) {
  const providers = (modelFactories || []).map((model) => [
    {
      provide: getModelToken(model.name),
      useFactory: async (...args: unknown[]) => {
        const object = await model.useFactory(...args);

        let modelDefinition: Omit<ModelDefinition, 'name'> | undefined;
        let schema: ModelDefinition['schema'] | undefined;

        if (object.hasOwnProperty('schema')) {
          modelDefinition = object as Omit<ModelDefinition, 'name'>;
          schema = modelDefinition.schema;
        } else {
          schema = object as ModelDefinition['schema'];
        }

        const options = modelDefinition?.options || model.options;
        const serializers = modelDefinition?.serializers || model.serializers;

        const modelInstance = dynamoose.model(model.name, schema, options);
        if (serializers) {
          Object.entries(serializers).forEach(([key, value]) => {
            modelInstance.serializer.add(key, value);
          });
        }
        return modelInstance;
      },
      inject: [DYNAMOOSE_INITIALIZATION, ...(model.inject || [])],
    },
  ]);
  return flatten(providers);
}
```

**Comment by geekmini** [comment]
Hi @hardyscc in terms of the backwards compatibility, I think it should support `name` field in both outside or inside the useFactory and the inside `name` should have higher priority over the outside `name`.

**Comment by hardyscc** [comment]
@geekmini  the outside name has to be static (bcos of nestjs provider) and @InjectModel required it as well, however the name can be remain inside, this mean the actual table name cannot different with the inject name.

```ts
export interface AsyncModelFactory
  extends Pick<ModuleMetadata, 'imports'>,
    Pick<ModelDefinition, 'name' | 'options' | 'serializers'> {
  useFactory: (
    ...args: any[]
  ) =>
    | ModelDefinition['schema']
    | Promise<ModelDefinition['schema']>
+   | ModelDefinition
+   | Promise<ModelDefinition>;
  inject?: any[];
}
```

```ts
export function createDynamooseAsyncProviders(
  modelFactories: AsyncModelFactory[] = [],
) {
  const providers = (modelFactories || []).map((model) => [
    {
      provide: getModelToken(model.name),
      useFactory: async (...args: unknown[]) => {
        const object = await model.useFactory(...args);

        let modelDefinition: ModelDefinition | undefined;
        let schema: ModelDefinition['schema'] | undefined;
        if (object.hasOwnProperty('schema')) {
          modelDefinition = object as ModelDefinition;
          schema = modelDefinition.schema;
        } else {
          schema = object as ModelDefinition['schema'];
        }
        const name = modelDefinition?.name || model.name;
        const options = modelDefinition?.options || model.options;
        const serializers = modelDefinition?.serializers || model.serializers;

        const modelInstance = dynamoose.model(name, schema, options);
        if (serializers) {
          Object.entries(serializers).forEach(([key, value]) => {
            modelInstance.serializer.add(key, value);
          });
        }
        return modelInstance;
      },
      inject: [DYNAMOOSE_INITIALIZATION, ...(model.inject || [])],
    },
  ]);
  return flatten(providers);
}

```

**Comment by geekmini** [comment]
Hi @hardyscc thanks for you explanation.

I have checked other nestjs modules, it also the same that model name is outside the useFactory function because it's used to genereate the provide token. Since `forFeatureAsync` is a sync function, there is no way to get the name from `await useFactory` inside the provide config.

I am happy to keep the name outside the useFactory, but for schema, options and serializer, i think it would be good to make it generated from the useFactory function so that client could have some space to inject configurations or other dependencies into the useFactory process.

What do you think? @hardyscc

**Comment by hardyscc** [comment]
@geekmini  Just released a beta version could you please help on testing, u can install it by
```sh
npm install nestjs-dynamoose@beta
```
I also add a additional property `tableName`, in case anyone don't want to use inject name as the table name (this feature has been requested before).

**Comment by ianzone** [comment]
> 
I'm I using it correctly? 
![image](https://user-images.githubusercontent.com/20043230/230714455-96a04c31-4f04-4d44-9b0a-8474430cbf92.png)

**Comment by ianzone** [comment]
> > 
> 
> I'm I using it correctly? ![image](https://user-images.githubusercontent.com/20043230/230714455-96a04c31-4f04-4d44-9b0a-8474430cbf92.png)

while ConfigModule is global

**Comment by ianzone** [comment]
more log @hardyscc 
![image](https://user-images.githubusercontent.com/20043230/230715517-0b288f49-a082-4fc7-81d7-add5d359cafb.png)

**Comment by hardyscc** [comment]
@ianzone  the first param is reserved,  also you need to add `inject`

```sh
    DynamooseModule.forFeatureAsync([
      {
        name: 'notification',
        useFactory: (_, configService: ConfigService) => {
          return {
            tableName: configService.get<string>('TABLE_NAME'),
            schema: NotificationSchema,
          };
        },
        inject: [ConfigService],
      },
    ]),
```

**Comment by ianzone** [comment]
> @ianzone the first param is reserved, also you need to add `inject`
> 
> ```shell
>     DynamooseModule.forFeatureAsync([
>       {
>         name: 'notification',
>         useFactory: (_, configService: ConfigService) => {
>           return {
>             tableName: configService.get<string>('TABLE_NAME'),
>             schema: NotificationSchema,
>           };
>         },
>         inject: [ConfigService],
>       },
>     ]),
> ```

It works, thank you very much! Better to have it documented to prevent hours of frustration for other people.

**Comment by hardyscc** [comment]
version 0.5.2 has been released, enjoy!
