### ISSUE TITLE
Adding migration

### ISSUE THREAD

**Issue by ThienNDDi** [hardyscc/nestjs-dynamoose#897]
## I'm submitting a new feature which can create migration for dynamodb.
right now i have to insert a data if i wanna create table.
Or may i missing it, can anyone help me to explain what i missed or i did wrong?

<pre><code>
[X] Feature request
</code></pre>
## Environment
<pre><code>
NestJS version: 10.1.10
NestJS Dynamoose version: 0.5.5
Dynamoose version: 3.2.0

 
For Tooling issues:
- Node version: v18.12.1 
- Platform:   Mac

</code></pre>

**Comment by hardyscc** [comment]
you should:

1. set the table create to false
2. run `npm run genres` to generate the resources/dynamodb.yml from schemas 
3. finally link it as a resources to your serverless.yaml

```js
    DynamooseModule.forRoot({
      table: {
        create: false,
      },
    }),
```
> please can refer to https://github.com/hardyscc/aws-nestjs-starter
