### ISSUE TITLE
Add missing Dynamoose Object functions

### ISSUE THREAD

**Issue by MickL** [hardyscc/nestjs-dynamoose#9]
Hey, great work! Maybe if you have time you could add a little more documentation? On the other hand I can find the most things in the interfaces and the dynamoose documentation so it might be okay.

Anyway, the first thing I would need is the `dynamoose.local();` option. I dont see it in the `DynamooseModuleOptions` interface. And what about other functions like `setDDB`? Would be nice to have it in the `DynamooseModuleOptions` or no?

Documentation: https://dynamoosejs.com/api/config/#dynamoose-object

**Comment by hardyscc** [comment]
@MickL Hi, I created this library in very short time to full-fill my need, still not go through all the Dynamoose's document yet. I will add the dbb and local support ASAP, however you can always do that by using DynamooseModule.forRootAsync() as follow :

```ts  
DynamooseModule.forRootAsync({
  useFactory: () => {
    dynamoose.aws.ddb.local('http://localhost:9000');
    return {
      model: {
        create: false,
      },
    };
  },
}),
```

The usage is mostly the same as [NestJS Mongoose](https://github.com/nestjs/mongoose), all the Typescript interfaces are included. You shouldn't have problem of using it ;)

**Comment by MickL** [comment]
Thank you :) Personally I just need `local` but it would be great if everything of Dynamoose is in :)

**Comment by hardyscc** [comment]
@MickL since we are using Dynamoose 2.0, please refer to the 2.0 documentation here
https://github.com/dynamoosejs/dynamoose/blob/master/docs/api/General.md

also @fishcharlie mention about the [Dynamoose 2.0 rewrite](https://github.com/dynamoosejs/dynamoose/issues/709)

> Look into changing dynamoose.aws.ddb & dynamoose.aws.converter both set & revert functions to use same system as Model.defaults where the user can just set a new value and we can access it.

so the api will mostly likely to be changed. in the meantime i will just add the local setting first.

**Comment by fishcharlie** [comment]
@hardyscc At this point, it's looking unlikely that `dynamoose.aws.ddb` or `dynamoose.aws.converter` will have breaking changes between now and v2.0 public release. I'd be curious to hear your thoughts on that task tho. I view it as pretty low priority, although not changing it now would require it to be held off until v3.

At the same time, I don't think the amount of dev time to fix it would be that large. So maybe it's worth doing it. What are your thoughts on that API and which do you think would be better?

**Comment by hardyscc** [comment]
@fishcharlie Thanks for your review :), keep it like that is good enough. I got some recommendation in mind, will write to you when I am free.
