### ISSUE TITLE
Config with unit test

### ISSUE THREAD

**Issue by Anhdao153** [hardyscc/nestjs-dynamoose#957]
I used your module connect to dynamoDb. It worked very good.
But now i wanna write unit.

But there were some problem
my unit test file
```
describe('MissionService', () => {
  let service: MissionService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [DynamooseModule.forFeature([MissionModel])],
      providers: [MissionService],
    }).compile();

    service = module.get<MissionService>(MissionService);
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });
});
```
here is my module
```
@Module({
  imports: [DynamooseModule.forFeature([MissionModel])],
  controllers: [MissionControllerAdmin],
  providers: [MissionService, MissionRepository],
  exports: [MissionService, MissionRepository],
})
export class MissionModule {}
```

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[X] Support request => [my post in stackoverflow.](https://stackoverflow.com/questions/77277788/config-unit-test-with-dynamoose-nestjs-jest)
</code></pre>

NestJS version: 9.0.0
NestJS Dynamoose version: i moved your source code into my project in 3 month ago
Dynamoose version: 3.2.0

**Comment by Anhdao153** [comment]
Please i really need your support.
Thanks very much

**Comment by hardyscc** [comment]
@Anhdao153 
please check this project first https://github.com/hardyscc/aws-nestjs-starter, which contains 100% code coverage test case
https://sonarcloud.io/component_measures?id=hardyscc_aws-nestjs-starter&metric=coverage&view=list

**Comment by Anhdao153** [comment]
@hardyscc Thanks, i resolved my problem, thanks very much.
Where is your donation's link?
